<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DomainPilot.App\DomainPilot.App.csproj" />
    <ProjectReference Include="..\DomainPilot.Core\DomainPilot.Core.csproj" />
    <ProjectReference Include="..\DomainPilot.Infrastructure\DomainPilot.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\DomainPilot.Desktop\MainWindow.xaml"
             Link="ui\MainWindow.xaml"
             CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\samples\bulk-users.template.csv"
             Link="samples\bulk-users.template.csv"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
